#!/bin/bash

#// HELP Menu

HELP () {

echo -e "

    ███╗   ███╗██╗  ██╗██████╗ ██████╗  ██████╗      ██╗
    ████╗ ████║██║ ██╔╝██╔══██╗██╔══██╗██╔═══██╗     ██║
    ██╔████╔██║█████╔╝ ██████╔╝██████╔╝██║   ██║     ██║
    ██║╚██╔╝██║██╔═██╗ ██╔═══╝ ██╔══██╗██║   ██║██   ██║
    ██║ ╚═╝ ██║██║  ██╗██║     ██║  ██║╚██████╔╝╚█████╔╝
    ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚════╝ 
                                                    
    mkproj (https://github.com/aatharvauti/mkproj)

    HELP MENU:

    {} required
    [] optional

    Usage: mkproj {Project Name} [Space-Separated Options] 

        -h, --help           Open this help menu
        -n, --name           Project Name
        -d, --default        Default Options
        -g, --gitignore      Use .gitignore
        -t, --tfa            2FA (Use this if you have 2FA activated for GitHub)
        -p, --public         Set GitHub Repository Visibility to Public
        -c, --code           Automatically opens Visual Studio Code

    Ex: mkproj -n MySexyPythonProject -p -t -c -g \"python,jupyternotebooks,linux,visualstudiocode,pycharm\"

"
exit
}

#// Argument Parser Switch Case

# initializing variables
CODE=false
PUBLIC=false
GITIGNORE=false
TFA=false
USERNAME="aatharvauti"
NAME=""

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            shift # past argument
            HELP
            ;;
        -d|--default)
            shift # past argument
            CODE=true
            TFA=true
            ;;
        -n|--name)
            NAME=$2
            shift # past argument
            shift # past value
            ;;
        -c|--code)
            shift # past argument
            CODE=true
            ;;
        -p|--public)
            shift # past argument
            PUBLIC=true
            ;;
        -g|--gitignore)
            VALUES_GI="$2"
            shift # past argument
            shift # past value
            GITIGNORE=true
            ;;
        -t|--tfa)
            shift # past argument
            TFA=true
            ;;
        -*|--*)
            echo "Unknown option $1"
            exit 1
            ;;
        *)
            POSITIONAL_ARGS+=("$1") # save positional arg
            shift # past argument
            ;;
    esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

#// Error
if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 "$1"
fi

#// Main Function
MAIN () {

    # create a new directory
    # create a README.md file and add # $NAME to it (tradition)
    echo "Creating Project ${NAME}"
    cd $HOME/code/ && mkdir $NAME && cd $NAME && touch README.md && echo "# ${NAME}" >> README.md
    
    # if gitignore it used
    if [ $GITIGNORE = true ]; then
        
        # toptal works on the value at the end of URL
        # to get list of all possible values, install gi command line and run "gi list"
        wget -c https://www.toptal.com/developers/gitignore/api/$VALUES_GI -O .gitignore 2>/dev/null
        
        # i use obsidian to edit markdown files, so adding .obsidian
        echo ".obsidian" >> .gitignore
        
        # logs are annoying
        echo ".log" >> .gitignore
    fi

    # 2 factor auth for github
    # this will further ask the user to enter OTP in their terminal to continue
    if [ $TFA = true ]; then
        
        # option to set repo visibility on github
        # by default all repos will be private
        if [ $PUBLIC = true ]; then
            echo "WARNING: Setting Repository Visibility to Public"
            # -W ignore ignores any warnings thrown by python
            python3 -W ignore $HOME/mkproj/mkrepo.py $NAME --public --tfa 
        else
            echo "Private"
            python3 -W ignore $HOME/mkproj/mkrepo.py $NAME --private --tfa
        fi
    else
        if [ $PUBLIC = true ]; then
            echo "WARNING: Setting Repository Visibility to Public"
            python3 -W ignore $HOME/mkproj/mkrepo.py $NAME --public
        else
            echo "Private"
            python3 -W ignore $HOME/mkproj/mkrepo.py $NAME --private
        fi
    fi

    # 2>/dev/null is used to supress the output
    git init 2>/dev/null
    
    # by default git init creates branch going by the name "master"
    # but github uses "main" as default
    # so we rename the branch
    git branch -M main
    
    # add remote origin to the local git repo
    git remote add origin git@github.com:$USERNAME/$NAME.git
    
    git add README.md && git commit -m "initial commit"
    git add .gitignore && git commit -m ".gitignore"
    
    git push -u origin main
    
    # for some reason geckodriver.log gets placed in our project folder
    rm geckodriver.log

    if [ $CODE = true ]; then
        echo "Opening Visual Studio Code"
        code .
    fi
}

MAIN